### ISSUE TITLE
Switching weapon reloads the musket

### ISSUE THREAD

**Issue by Johuotar** [jukeri12/musket-doom#5]
Steps to reproduce:
1 Switch to musket
2 Fire musket
3 Switch to pistol -> Your musket starts reloading

**Comment by jukeri12** [comment]
Have no idea. Gotta check up on weapon switching logic and probably reload logic in p_pspr.c

**Comment by jukeri12** [comment]
I found out that you can "switch" to your pistol while the pistol is equipped when it is not loaded and then it begins reloading.

Like this:
-Shoot pistol
-Press 2 to switch back to pistol
--> reloading begins

So it has to be something to do with input code.

**Comment by jukeri12** [comment]
It was something to do with the input code. Since the commands have bit values defined to them and the reload command was defined with same bit value as weaponchange (that is 8) it thought both commands/buttons were being accessed at the same time.

It is now mapped to 2 (check d_event.h) which means it confuses it with the use command, but use command is probably not of much use in this game (as of now no use) and it is definitely less annoying than involuntarily reloading.

Still needs adjustment so that the use button is not triggering when reloading, but it is mostly not visible unless you face a wall, so closing this issue. In the future we could remove the Use command entirely if need be
